schema: ./src/schema.graphql
generates:
  ./src/schemaTypes.ts:
    config:
      contextType: ./GQLContext#GQLContext
      mappers:
        User: ./models/UserModel#UserModel
        Comic: ./models/ComicModel#ComicModel
      useIndexSignature: true
      scalars:
        DateTime: Date
        JSON: any
    plugins:
      - typescript
      - typescript-resolvers
